name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run tests
        run: make pipeline-test

  deploy:
    name: Build + deploy application
    runs-on: ubuntu-latest
    needs: [test]

    # Env variables get injected into bash scripts.
    # `secrets.*` come from the GitHub repository settings.
    env:
      HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
      HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy to Heroku
        run: make pipeline-deploy
