version: "3.7"

####################### Services Definition #######################
services:
  server-development:
    image: server:development
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      target: "development"
    volumes:
      - "./:/usr/src/app"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
