name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build + deploy server and client
    runs-on: ubuntu-latest

    # Env variables get injected into bash scripts.
    # `secrets.*` come from the GitHub repository settings.
    env:
      HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
      HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      HEROKU_SERVER_APP_NAME: ${{ secrets.HEROKU_SERVER_APP_NAME }}
      HEROKU_CLIENT_APP_NAME: ${{ secrets.HEROKU_CLIENT_APP_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to Heroku
        run: make pipeline-heroku-login

      - name: Deploy server
        run: make pipeline-deploy-server

      - name: Deploy client
        run: make pipeline-deploy-client
